import os, time
from typing import Optional

from textarena.core import Agent, extract_action

__all__ = ["HumanAgent", "OpenRouterAgent", "TinkerAgent"]
STANDARD_GAME_PROMPT = (
    "You are a competitive game player. Make sure you read the game instructions carefully. "
    "You may reason freely in your response, but you must provide your final action inside "
    "<action>...</action> tags, e.g. <action>your action here</action>. "
    "Only the content inside the tags is submitted to the game."
)
    

class HumanAgent(Agent):
    """ Human agent class that allows the user to input actions manually """
    def __init__(self):
        super().__init__()

    def __call__(self, observation: str) -> str:
        """
        Process the observation and return the action.
        
        Args:
            observation (str): The input string to process.
            
        Returns:
            str: The response generated by the agent.
        """
        print("\n\n+++ +++ +++") # for easies visualization of what is part of each turns observation
        return extract_action(input(f"Current observations: {observation}\nPlease enter the action: "))


class OpenRouterAgent(Agent):
    """ Agent class using the OpenRouter API to generate responses. """
    def __init__(self, model_name: str, system_prompt: Optional[str] = STANDARD_GAME_PROMPT, verbose: bool = False, **kwargs):
        """
        Args:
            model_name (str): The name of the model.
            system_prompt (Optional[str]): The system prompt to use (default: STANDARD_GAME_PROMPT)
            verbose (bool): If True, additional debug info will be printed.
            **kwargs: Additional keyword arguments to pass to the OpenAI API call.
        """
        super().__init__()
        self.model_name = model_name 
        self.verbose = verbose 
        self.system_prompt = system_prompt
        self.kwargs = kwargs

        try:
            from openai import OpenAI
            from openai._exceptions import OpenAIError
        except ImportError:
            raise ImportError("OpenAI package is required for OpenRouterAgent. Install it with: pip install openai")
        
        api_key = os.getenv("OPENROUTER_API_KEY") # Set the open router api key from an environment variable
        if not api_key:
            raise ValueError("OpenRouter API key not found. Please set the OPENROUTER_API_KEY environment variable.")
        self.client = OpenAI(base_url="https://openrouter.ai/api/v1", api_key=api_key)

    def _make_request(self, observation: str) -> str:
        """ Make a single API request to OpenRouter and return the generated message. """
        messages = [{"role": "system", "content": self.system_prompt}, {"role": "user", "content": observation}]
        response = self.client.chat.completions.create(model=self.model_name, messages=messages, n=1, stop=None, **self.kwargs)
        return response.choices[0].message.content.strip()

    def _retry_request(self, observation: str, retries: int = 3, delay: int = 5) -> str:
        """
        Attempt to make an API request with retries.

        Args:
            observation (str): The input to process.
            retries (int): The number of attempts to try.
            delay (int): Seconds to wait between attempts.

        Raises:
            Exception: The last exception caught if all retries fail.
        """
        last_exception = None
        for attempt in range(1, retries + 1):
            try:
                response = self._make_request(observation)
                if self.verbose:
                    print(f"\nObservation: {observation}\nResponse: {response}")
                return response

            except Exception as e:
                last_exception = e
                print(f"Attempt {attempt} failed with error: {e}")
                if attempt < retries:
                    time.sleep(delay)
        raise last_exception

    def __call__(self, observation: str) -> str:
        """
        Process the observation using the OpenRouter API and return the action.

        Args:
            observation (str): The input string to process.

        Returns:
            str: The action extracted from the model's <action>...</action> tags.
        """
        if not isinstance(observation, str):
            raise ValueError(f"Observation must be a string. Received type: {type(observation)}")
        return extract_action(self._retry_request(observation))


class TinkerAgent(Agent):
    """ Agent class using the Tinker API (Thinking Machines) to sample from base or fine-tuned models.

    Point it at a base model (e.g. model_name="Qwen/Qwen3-8B") or at weights saved from a
    Tinker training run (e.g. model_path="tinker://run-id/weights/checkpoint-001"), which makes
    it easy to evaluate checkpoints you fine-tuned on TextArena games.
    """
    def __init__(self, model_name: Optional[str]=None, model_path: Optional[str]=None,
                 system_prompt: Optional[str]=STANDARD_GAME_PROMPT, max_tokens: int=1024,
                 temperature: float=0.7, verbose: bool=False, **sampling_kwargs):
        """
        Args:
            model_name (Optional[str]): Name of the base model to sample from (e.g. "Qwen/Qwen3-8B").
            model_path (Optional[str]): Path to saved model weights (e.g. "tinker://run-id/weights/checkpoint-001").
                Provide exactly one of model_name / model_path.
            system_prompt (Optional[str]): The system prompt to use (default: STANDARD_GAME_PROMPT).
            max_tokens (int): The maximum number of tokens to generate.
            temperature (float): The sampling temperature.
            verbose (bool): If True, additional debug info will be printed.
            **sampling_kwargs: Additional keyword arguments passed to tinker.types.SamplingParams (e.g. top_p, stop).
        """
        super().__init__()
        if (model_name is None) == (model_path is None):
            raise ValueError("Provide exactly one of 'model_name' (a base model) or 'model_path' (a tinker:// checkpoint).")
        self.model_name = model_name
        self.model_path = model_path
        self.system_prompt = system_prompt
        self.verbose = verbose

        try:
            import tinker
            from tinker import types
        except ImportError:
            raise ImportError("Tinker package is required for TinkerAgent. Install it with: pip install tinker")
        self._types = types

        if not os.getenv("TINKER_API_KEY"):
            raise ValueError("Tinker API key not found. Please set the TINKER_API_KEY environment variable.")

        self.service_client = tinker.ServiceClient()
        self.sampling_client = self.service_client.create_sampling_client(base_model=model_name, model_path=model_path)
        self.tokenizer = self.sampling_client.get_tokenizer()
        self.sampling_params = types.SamplingParams(max_tokens=max_tokens, temperature=temperature, **sampling_kwargs)

    def _build_prompt(self, observation: str):
        """ Build a tinker ModelInput, using the model's chat template when available. """
        if getattr(self.tokenizer, "chat_template", None):
            messages = [{"role": "system", "content": self.system_prompt}, {"role": "user", "content": observation}]
            token_ids = self.tokenizer.apply_chat_template(messages, add_generation_prompt=True, tokenize=True)
        else: # base model without a chat template: fall back to a plain-text prompt
            token_ids = self.tokenizer.encode(f"{self.system_prompt}\n\n{observation}\n")
        return self._types.ModelInput.from_ints(token_ids)

    def _make_request(self, observation: str) -> str:
        """ Make a single sampling request to Tinker and return the generated message. """
        prompt = self._build_prompt(observation)
        result = self.sampling_client.sample(prompt=prompt, sampling_params=self.sampling_params, num_samples=1).result()
        return self.tokenizer.decode(result.sequences[0].tokens, skip_special_tokens=True).strip()

    def _retry_request(self, observation: str, retries: int=3, delay: int=5) -> str:
        """
        Attempt to make a sampling request with retries.

        Args:
            observation (str): The input to process.
            retries (int): The number of attempts to try.
            delay (int): Seconds to wait between attempts.

        Raises:
            Exception: The last exception caught if all retries fail.
        """
        last_exception = None
        for attempt in range(1, retries + 1):
            try:
                response = self._make_request(observation)
                if self.verbose:
                    print(f"\nObservation: {observation}\nResponse: {response}")
                return response
            except Exception as e:
                last_exception = e
                print(f"Attempt {attempt} failed with error: {e}")
                if attempt < retries:
                    time.sleep(delay)
        raise last_exception

    def __call__(self, observation: str) -> str:
        """
        Process the observation using the Tinker API and return the generated response.

        Args:
            observation (str): The input string to process.

        Returns:
            str: The action extracted from the model's <action>...</action> tags.
        """
        if not isinstance(observation, str):
            raise ValueError(f"Observation must be a string. Received type: {type(observation)}")
        return extract_action(self._retry_request(observation))
